name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
  
    strategy:
      matrix:
        context: 
        - others

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export Base to Docker
        uses: docker/build-push-action@v3
        with:
          context: base
          load: true
          tags: user/tomcat-base

      - name: Images Verify
        run: docker image ls -a

      - name: Test
        run: |
          docker run --rm user/tomcat-base

      - name: Build and Export to Docker
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
